name = "ecoliglycolysisandppp"
kinetic_model_file = "kinetic_model.toml"
priors_file = "priors.toml"
experiments_file = "experiments.toml"
likelihood = true
reject_non_steady = false

[cmdstanpy_config]
iter_warmup = 200
iter_sampling = 100
chains = 2
save_warmup = true
refresh = 1
metric = "dense"
max_treedepth = 5
show_console = false


[ode_config]
rel_tol = 1e-9
abs_tol = 1e-9
max_num_steps = 1e9
timepoint = 1e6
